
#Uses node version 22 as a base image 
FROM node:22 

#Goes to the app directory
WORKDIR /app

COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy all backend files
COPY backend/ .

# Expose port 
EXPOSE 5000

#Run the backend
CMD ["node", "index.js"]
